"""The per-label-set table for the repository README, built from what the runs measured.

    python training/compare.py            # print it
    python training/compare.py --write    # replace the section in README.md

Each model card carries its own numbers; nobody comparing two of them should have to open two tabs.
The reports are read from the Hub, so the table says what is published rather than what is on disk.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import urllib.request

MODELS = (("base", "lenabarretta/sharada-base"),
          ("large", "lenabarretta/sharada-large"),
          ("multilingual", "lenabarretta/sharada-multilingual-base"))
MARK = "<!-- per-label-set table, generated by training/compare.py -->"


def report(repo: str) -> dict:
    local = pathlib.Path("runs") / repo.split("/")[-1].replace("sharada-", "") / "report.json"
    if local.exists():
        return json.loads(local.read_text())
    with urllib.request.urlopen(f"https://huggingface.co/{repo}/resolve/main/report.json") as r:
        return json.load(r)


def table() -> str:
    reports = {name: report(repo) for name, repo in MODELS}
    datasets = {s["task"]: s for r in reports.values() for s in r["sources"]}
    tasks: dict[str, dict] = {}
    for name, r in reports.items():
        for task, row in r["per_task"].items():
            tasks.setdefault(task, {})[name] = row

    def sort_key(item):
        task, by_model = item
        any_row = next(iter(by_model.values()))
        return (any_row["trained_on"], any_row["options"], task)

    trained = {name: r.get("training_per_task", {}) for name, r in reports.items()}
    lines = [MARK,
             "| label set | answer options | trained on | measured on "
             "| base | large | multilingual | what it is |",
             "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for task, by_model in sorted(tasks.items(), key=sort_key, reverse=True):
        source = datasets.get(task, {})
        unseen = not next(iter(by_model.values()))["trained_on"]
        where = source.get("dataset", "—")
        if source.get("configs"):
            where += f" ×{len(source['configs'])} languages"
        elif source.get("config"):
            where += f"/{source['config']}"
        cells = [f"{by_model[n]['accuracy']:.3f}" if n in by_model else "—" for n, _ in MODELS]
        name = f"{task} *(unseen)*" if unseen else task
        seen = max((trained[n].get(task, 0) for n, _ in MODELS), default=0)
        any_row = next(iter(by_model.values()))
        lines.append(f"| {name} | {any_row['options']} | {f'{seen:,}' if seen else '—'} "
                     f"| {any_row['n']:,} | {' | '.join(cells)} | `{where}` |")

    overall = " | ".join(f"**{reports[n]['overall']['accuracy']:.3f}**" for n, _ in MODELS)
    totals = max(sum(t.values()) for t in trained.values())
    measured = max(r["held_out_examples"] for r in reports.values())
    lines.append(f"| **overall** | | **{totals:,}** | **{measured:,}** | {overall} | |")
    lines.append(MARK)
    return "\n".join(lines)


def main() -> None:
    parse = argparse.ArgumentParser(description=__doc__)
    parse.add_argument("--write", action="store_true", help="replace the section in README.md")
    args = parse.parse_args()

    rendered = table()
    if not args.write:
        print(rendered)
        return
    readme = pathlib.Path("README.md")
    text = readme.read_text()
    if text.count(MARK) != 2:
        sys.exit(f"README.md needs two {MARK} lines marking where the table goes")
    before, _, rest = text.partition(MARK)
    _, _, after = rest.partition(MARK)
    readme.write_text(before + rendered + after)
    print(f"README.md updated, {rendered.count(chr(10))} lines")


if __name__ == "__main__":
    main()
